### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/smallsemi#23]
The last one was 2019-08-16 and a bunch of changes have accumulated. Perhaps also merge PR #21, if you like.

**Comment by fingolfin** [comment]
If you prefer, I am also happy to make that release for you, it'll take me just 5 minutes or so

**Comment by fingolfin** [comment]
Done, 0.6.13 is out

**Comment by james-d-mitchell** [comment]
I don't seem to have write access to this repo any longer :( @fingolfin

**Comment by fingolfin** [comment]
@james-d-mitchell simple, you never accepted the invitation to become admin of this repo. I just resent it. Please check your email

**Comment by james-d-mitchell** [comment]
Thanks @fingolfin!

I think this issue can be closed, right?
