### ISSUE TITLE
README references archives for 0.6.13

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/smallsemi#44]
The README contains stuff like this in a few places:
> Download the archive 'smallsemi-0.6.13.tar.gz' from

This should be updated I guess?

If this was my project I would in fact remove all mentions of the
version from the README just so I wouldn't have to worry about this, but
of course that's entirely up to the authors.

**Comment by james-d-mitchell** [comment]
Good point, I'll make a PR for this! Thanks for the suggestion @fingolfin
