### ISSUE TITLE
SmallsemiTestManualExamples does not work anymore

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-packages/smallsemi#6]
It looks like the documentation setup has changed, and as a consequence `SmallsemiTestManualExamples` doesn't any longer work.

**Comment by fingolfin** [comment]
I've got an alternative for this, by using AutoDoc's `extract_examples` feature (requires a recent AutoDoc version), I can submit a PR for using that in this package if you are interested.

**Comment by olexandr-konovalov** [comment]
Can this be now closed - after merging #12 ?

**Comment by james-d-mitchell** [comment]
Yup, thanks for the input @alex-konovalov and @fingolfin
